### ISSUE TITLE
Disappearing of part in 3D Electronics

### ISSUE THREAD

**Issue by smuharek** [platsch/Slic3r#5]
### Version
0.9.9-3415-g19f5cdd
### Operating system type + version
Ubuntu 16.04 LTS

### Behavior
* _Describe the problem_
When Placing a electronic part and moving it after first placement the whole part is disappearing and just the coordinate axes are shown.
When you further move the part with the buttons on the lower left corner the part is appearing again.
* _Steps needed to reproduce the problem_
just place a electronic part on the base part and move it. 

* _Expected Results_
no disappearing of the whole part

  * _Screenshots from __*Slic3r*__ preview are preferred_
Diasappeared part:
![grafik](https://user-images.githubusercontent.com/39057336/39800942-e0168c9e-5369-11e8-913d-2294f610eee3.png)
Appeared part:
![grafik](https://user-images.githubusercontent.com/39057336/39800964-f12b3e8a-5369-11e8-8096-6ae636d283e6.png)

#### STL/Config (.ZIP) where problem occurs
_Upload a zipped copy of an STL and your config (`File -> Export Config`)_
[stl_config.zip](https://github.com/platsch/Slic3r/files/1986768/stl_config.zip)

**Comment by platsch** [comment]
Seems to be related to background processing. Could you please try to enable it via `File -> Preferences -> Background processing` and try again?

It is supposed to work without background processing enabled, but it would narrow the debugging scope quite a bit.

**Comment by platsch** [comment]
Should be fixed with 6150c471afeb6527f0a486a616d8b34337b6e69a

**Comment by smuharek** [comment]
With enabling the background processing it's fine. The whole part is disappearing but appears after a second and one can continue work.
Thank you.

**Comment by platsch** [comment]
Yes, it disappears because the whole toolpath gets regenerated with the new part position. Depending on the object's size and complexity this can take some time.
